FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
	ffmpeg \
	nvidia-cudnn \
	python3 \
	python3-pip \
	python3-tk \
	python-is-python3
