FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
	ffmpeg \
	nvidia-cudnn \
	python3 \
	python3-pip \
	python3-tk \
	python-is-python3

WORKDIR /app

ADD requirements.txt .
RUN pip install -r requirements.txt

ADD inswapper_128.onnx .
ADD run.py .
ADD roop roop

ENV HOME=/cache

RUN mkdir /cache

ENTRYPOINT ["python", "/app/run.py"]
